Add files via upload
Improved error-correction.

diff --git a/check_sonicwall_cpu b/check_sonicwall_cpu
--- a/check_sonicwall_cpu
+++ b/check_sonicwall_cpu
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 #################################################
 #						#
 # Nagios Sonicwall cpu-check met notificatie	#
@@ -5,11 +7,7 @@
 # 						#
 # Copyright Vincent Lieftink			#
 # MHASMO bv					#
-# This script depends on check_snmp		#
 #################################################
-
-
-#!/bin/bash					
 
 # Global variables:
 PATH='/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
@@ -23,22 +21,28 @@ STATE_UNKNOWN="3"
 HOST="$2"
 
 # This is where the magic happens
-checkcpu=`/home/nagios/bin/check_snmp -H $HOST -C public -o .1.3.6.1.4.1.8741.1.3.1.3.0 | awk {'print $4'}`
+CHECKCPU=`/home/nagios/bin/check_snmp -H $HOST -C public -o .1.3.6.1.4.1.8741.1.3.1.3.0 | awk {'print $4'}`
 
 # Worden er argumenten meegegeven?
 [ ${#} = 2 ] || {   echo "Usage: ${SCRIPT_PATH} -H <SERVER-IP>" ; exit "${STATE_UNKNOWN}"; }
 
 
+# Controleren of variable $CHECK inderdaad een getal is.
+if ! [[ $CHECKCPU =~ ^-?[0-9]+$ ]] ; then
+        echo "ERROR! Invalid response!"
+        exit $STATE_UNKNOWN
+fi
+
 # Check-load adv treshold
-if [ $checkcpu -gt 95 ]
+if [ $CHECKCPU -gt 95 ]
 then
-	echo "CRITICAL! High cpu%-utilization detected! = $checkcpu% | 'SONICWALL-CPU-UTILIZATION'=$checkcpu% "
+	echo "CRITICAL! High cpu%-utilization detected! = $CHECKCPU% | 'SONICWALL-CPU-UTILIZATION'=$CHECKCPU% "
 	exit ${STATE_CRITICAL} 
-elif [ $checkcpu -gt 80 ]
+elif [ $CHECKCPU -gt 80 ]
 then
-	echo "WARNING! High cpu%-utilization detected! = $checkcpu% | 'SONICWALL-CPU-UTILIZATION'=$checkcpu%"
+	echo "WARNING! High cpu%-utilization detected! = $CHECKCPU% | 'SONICWALL-CPU-UTILIZATION'=$CHECKCPU%"
 	exit ${STATE_WARNING}
 else
-	echo "OK! Normal cpu%-utilization = $checkcpu% | 'SONICWALL-CPU-UTILIZATION'=$checkcpu%"
+	echo "OK! Normal cpu%-utilization = $CHECKCPU% | 'SONICWALL-CPU-UTILIZATION'=$CHECKCPU%"
 	exit ${STATE_OK}
 fi
diff --git a/check_sonicwall_mem b/check_sonicwall_mem
--- a/check_sonicwall_mem
+++ b/check_sonicwall_mem
@@ -1,14 +1,14 @@
+#!/bin/bash
+
 #################################################
 #						#
-# Nagios Sonicwall cpu-check met notificatie	#
+# Nagios Sonicwall cpu-CHECK met notificatie	#
 # Versie 1.0					#
 # 						#
 # Copyright Vincent Lieftink			#
 # MHASMO bv					#
 #################################################
 
-
-#!/bin/bash					
 
 # Global variables:
 PATH='/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
@@ -22,22 +22,27 @@ STATE_UNKNOWN="3"
 HOST="$2"
 
 # This is where the magic happens
-check=`/home/nagios/bin/check_snmp -H $HOST -C public -o .1.3.6.1.4.1.8741.1.3.1.4.0 | awk {'print $4'}`
+CHECK=`/home/nagios/bin/check_snmp -H $HOST -C public -o .1.3.6.1.4.1.8741.1.3.1.4.0 | awk {'print $4'}`
 
 # Worden er argumenten meegegeven?
 [ ${#} = 2 ] || {   echo "Usage: ${SCRIPT_PATH} -H <SERVER-IP>" ; exit "${STATE_UNKNOWN}"; }
 
+# Controleren of variable $CHECK inderdaad een getal is.
+if ! [[ $CHECK =~ ^-?[0-9]+$ ]] ; then
+        echo "ERROR! Invalid response!"
+        exit $STATE_UNKNOWN
+fi
 
-# Check-load adv treshold
-if [ $check -gt 90 ]
+# CHECK-load adv treshold
+if [ $CHECK -gt 90 ]
 then
-	echo "CRITICAL! High mem%-utilization detected! = $check% | 'SONICWALL-MEM-UTILIZATION'=$check%"
+	echo "CRITICAL! High mem%-utilization detected! = $CHECK% | 'SONICWALL-MEM-UTILIZATION'=$CHECK%"
 	exit ${STATE_CRITICAL} 
-elif [ $check -gt 80 ]
+elif [ $CHECK -gt 80 ]
 then
-	echo "WARNING! High mem%-utilization detected! = $check% | 'SONICWALL-MEM-UTILIZATION'=$check%"
+	echo "WARNING! High mem%-utilization detected! = $CHECK% | 'SONICWALL-MEM-UTILIZATION'=$CHECK%"
 	exit ${STATE_WARNING}
 else
-	echo "OK! Normal mem%-utilization = $check% | 'SONICWALL-MEM-UTILIZATION'=$check%"
+	echo "OK! Normal mem%-utilization = $CHECK% | 'SONICWALL-MEM-UTILIZATION'=$CHECK%"
 	exit ${STATE_OK}
 fi
